"""Constants for Hunt Configuration"""

DEFAULT_TARGET_KEY = "TAB"
DEFAULT_TARGET_CYCLE_DELAY = 0.2
DEFAULT_SEARCH_INTERVAL = 0.25
DEFAULT_ATTACK_INTERVAL = 0.15
DEFAULT_LOST_TIMEOUT = 1.2
DEFAULT_ATTACK_MIN_DURATION = 1.5
DEFAULT_ATTACK_PRESS_MS = 60

# Global Hotkeys
DEFAULT_START_HOTKEY = "ctrl+shift+r"
DEFAULT_STOP_HOTKEY = "ctrl+shift+e"
DEFAULT_LIBRARY_MANAGER_KEY = "ctrl+shift+l"
DEFAULT_VISION_WIZARD_KEY = "ctrl+shift+v"
DEFAULT_MONSTER_EDITOR_KEY = "ctrl+shift+m"
